<template>
  <div class="h-full w-full flex flex-col justify-center items-center">
    <div class="rotate-center border-dashed border-2 border-black w-16 h-16 rounded-full"></div>
  </div>
</template>



<style scoped>


/* ----------------------------------------------
 * Generated by Animista on 2021-4-25 13:20:15
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-center
 * ----------------------------------------
 */

 .rotate-center {
	-webkit-animation: rotate-center 5s linear infinite both;
	        animation: rotate-center 5s linear infinite both;
}

@-webkit-keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}
@keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}

</style>




